### ISSUE TITLE
[question] flattening tables

### ISSUE THREAD

**Issue by mirabilos** [matthewwithanm/python-markdownify#105]
Hi,

(background: using markdownify to convert RSS feeds’ posts’ HTML to Md to post on Fediverse)

is there a chance to get a functionality that flattens down tables into something else (paragraphs, lists, …) for [environments that don’t allow the Md tables extension](https://github.com/superseriousbusiness/gotosocial/issues/2554)?

Is that better done here or on a preprocessing later before (with bs4 maybe? I don’t know about bs4 *at all*, unfortunately; I don’t use Python3 much)?

**Comment by chrispy-snps** [comment]
@mirabilos - do you have examples of how you'd *like* to see this conversion work?

One of the challenges with HTML-to-Markdown conversion of tables is that HTML table cells can include complex content (multiple paragraphs, nested lists, blockquotes, and even more tables). What is the most complex table cell content your use case might encounter?
