### ISSUE TITLE
<b></b> without training space

### ISSUE THREAD

**Issue by AlexVonB** [matthewwithanm/python-markdownify#13]
Hi!

Sorry for spamming comments on your great project! I found that

```html
<b>foo </b>bar
```

gets translated to

```markdown
**foo **bar
```

which gets rendered as

**foo **bar

but should render as

**foo** bar

This one requires more than one change:

- Removing the trailing (and leading, for that matter) spaces inside an inline tag (not only `<b>`)
- If a leading space was removed, add as space before the opening `**`
- If a trailing space was removed, add a space after the closing `**`

If you don't see any problems with this change, I would create a PR with tests.

Best!
Alex

**Comment by matthewwithanm** [comment]
Good call!
