### ISSUE TITLE
Fragment links using id are removed

### ISSUE THREAD

**Issue by ngtw-j** [matthewwithanm/python-markdownify#133]
## Issue
Given a html file with a fragment:
```html
// article.html
<a href="#pookie"></a>

/* 
 * more html
*/
<h2 id="pookie"></h2>
```
The equivalent md generated will be 

```md
// article.md
[pookie](#pookie)

// more md

// fragment is removed
```

when it should look like 
```md
// article.md
[pookie](#pookie)

// more md

# pookie
```

## Possible Solution
Store a dictionary of id and when id is encountered again, replace with corresponding `#id`

**Comment by AlexVonB** [comment]
Thanks for reporting this. I am afraid this is a bit out of scope for this project. In your proposed solution, we would need to guess what text to put in the headline and then print a headline that was not there before. You could preprocess the file and replace all empty headlines with `&nbsp`, for example.
