### ISSUE TITLE
Colspan int casting untreated error

### ISSUE THREAD

**Issue by FHaggs** [matthewwithanm/python-markdownify#137]
File \"/usr/local/lib/python3.12/site-packages/markdownify/__init__.py\", line 422, in markdownify
    return MarkdownConverter(**options).convert(html)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.12/site-packages/markdownify/__init__.py\", line 97, in convert
    return self.convert_soup(soup)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.12/site-packages/markdownify/__init__.py\", line 100, in convert_soup
    return self.process_tag(soup, convert_as_inline=False, children_only=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.12/site-packages/markdownify/__init__.py\", line 143, in process_tag
    text += self.process_tag(el, convert_children_as_inline)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.12/site-packages/markdownify/__init__.py\", line 143, in process_tag
    text += self.process_tag(el, convert_children_as_inline)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.12/site-packages/markdownify/__init__.py\", line 143, in process_tag
    text += self.process_tag(el, convert_children_as_inline)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 3 more times]
  File \"/usr/local/lib/python3.12/site-packages/markdownify/__init__.py\", line 148, in process_tag
    text = convert_fn(node, text, convert_as_inline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.12/site-packages/markdownify/__init__.py\", line 387, in convert_th
    colspan = int(el['colspan'])
              ^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\\\\\"2\\\\\"'

When using the md function this may happen

**Comment by AlexVonB** [comment]
Thanks! This was just fixed in v0.13.0
