### ISSUE TITLE
Markdownify conversion results in extra `\` before end parentheses `)` 

### ISSUE THREAD

**Issue by vivienneprince** [matthewwithanm/python-markdownify#140]
Example:

```py
from markdownify import markdownify as md

example_html = '<h2>Example Heading (Heading 2)</h2>'
mdtxt = md(example_html, heading_style = 'ATX')

>>> ## Example Heading (Heading 2\)
```

It doesn't consistently happen; sometimes end parentheses in headings have no issues. 

So far I haven't seen this happen within p tags, but I have seen some periods (`.`) get converted into `\.` in p tags.

**Comment by AlexVonB** [comment]
This was fixed by #149 and is present in 0.14.0. Thanks for reporting!
