### ISSUE TITLE
Formatting inside code spans

### ISSUE THREAD

**Issue by jonatanschroeder** [matthewwithanm/python-markdownify#141]
Consider the following construct:
```
<code>normal <strong>bold</strong></code>
```
This is valid HTML, and will cause "bold" to be formatted in bold. markdownify causes the `strong` tag to be lost, though:

```
>>> md('<code>normal <strong>bold</strong></code>')
'`normal bold`'
```

**Comment by chrispy-snps** [comment]
@jonatanschroeder - Markdown does not support formatting inside code spans or code blocks; characters inside these elements (thus including styling elements) are displayed literally.

**Comment by jonatanschroeder** [comment]
Indeed, so if the intention is to create markdown that can be converted back to equivalent HTML this loses information, as converting it back will not include that formatting. If that is not the intention then I may have misunderstood the purpose of the library.

**Comment by chrispy-snps** [comment]
The purpose is to convert HTML to Markdown, but that is an inherently lossy process as Markdown cannot represent everything that HTML can.

There is a "backdoor" in Markdown for such cases where you can intermix HTML and Markdown syntax in a Markdown document, but most of us converting HTML to Markdown are trying to get away from HTML entirely (for simplified text processing, etc.).

**Comment by jonatanschroeder** [comment]
Noted. I will close the issue then.

**Comment by chrispy-snps** [comment]
@jonatanschroeder - for what it's worth, we also wish Markdown supported formatting inside code spans and blocks. Our HTML makes heavy use of emphasizing things inside `<pre>` blocks. When we convert it to Markdown for LLM use, the emphasis is lost.

**Comment by jinhucheung** [comment]
> [@jonatanschroeder](https://github.com/jonatanschroeder) - for what it's worth, we also wish Markdown supported formatting inside code spans and blocks. Our HTML makes heavy use of emphasizing things inside `\<pre\>` blocks. When we convert it to Markdown for LLM use, the emphasis is lost.

I totally agree :+1:

**Comment by chrispy-snps** [comment]
Even [Pandoc](https://pandoc.org/) has this limitation. Its internal content AST (abstract syntax tree) is Markdown-like. So if you are translating between formats that **do** support formatting in code spans and blocks, the formatting is lost anyway.

**Comment by jonatanschroeder** [comment]
For reference, I tried other libraries as well (both in Python and JS/TS) and most of them have the same limitation. There is a TS project that actually attempts to keep info where it would be lost, called [HTMLarkdown](https://github.com/EvitanRelta/htmlarkdown), but it hasn't been maintained for a while and has its own issues.
