### ISSUE TITLE
title gets mangled into href for <a title="x"> 

### ISSUE THREAD

**Issue by hnykda** [matthewwithanm/python-markdownify#157]
```
from markdownify import markdownify as md

print(
    md(
        """
<a href="/some/" title="Read 'This' Man">Does not work</a>
"""
    )
)
```
shows
```
[Does not work](/some/ "Read 'This' Man")
```

instead of:
```
[Does not work](/some/)
```

**Comment by AlexVonB** [comment]
Hey, what output do you expect? Your 

```
[Does not work](/some/ "Read 'This' Man")
```

renders as

[Does not work](/some/ "Read 'This' Man")

(Screenshot for clarity:

![grafik](https://github.com/user-attachments/assets/cbf10565-a269-41ff-9785-123eb51dbdf1)

)

which shows the title on hover.

**Comment by hnykda** [comment]
WHAT? Have I been living under a rock and not knowing about this aspect of markdown. Really sorry, thanks for your work!

**Comment by AlexVonB** [comment]
No worries, glad to help :)
