### ISSUE TITLE
How to iteratively transform subpages within an HTML document?

### ISSUE THREAD

**Issue by SetonLiang** [matthewwithanm/python-markdownify#160]
I want to convert some personal homepage HTML data into Markdown format. However, there will be many subpages, like
![image](https://github.com/user-attachments/assets/305fa66d-3a4b-4a4b-8cb9-d8800d5a604e)

How can I iterate through these subpages and convert them into the corresponding Markdown format with their titles?
```
loader = AsyncHtmlLoader(urls)
docs = loader.load()

# 转换HTML到Markdown
md = MarkdownifyTransformer()
converted_docs = md.transform_documents(docs)

# 输出转换结果
print(converted_docs[0].page_content[:5000])
```

**Comment by AlexVonB** [comment]
You would want to crawl the page with something like https://scrapy.org/ . Closing this, because this is not possible just with this lib.
