### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by desmap** [matthewwithanm/python-markdownify#28]
Just ran into the leading whitespace issue and wondering if this repo is still maintained...

**Comment by matthewwithanm** [comment]
Yeah, @AlexVonB pushed a new release just two weeks ago!

**Comment by desmap** [comment]
Great that you are responsive! The "new release" two weeks ago was just a version bump. Would you mind to look into https://github.com/matthewwithanm/python-markdownify/issues/17 ? Thanks!

**Comment by AlexVonB** [comment]
Sorry for that, it seems that I did not get notifications for any of that. I'll have a look! Thanks!
