### ISSUE TITLE
Exclude comments

### ISSUE THREAD

**Issue by BrunoMiguens** [matthewwithanm/python-markdownify#33]
Currently markdownify allows to parse comments, might not very common to see comments (`<!--` & `-->`) in HTML however when you're working with someones HTML code anything can happen.

### Did write a test to check that:
```python
def test_comments():
    text = md("<!-- This is a comment -->")
    assert text == ""
``` 

The test above should pass, however, the response is ` This is a comment ` and it shouldn't be.

### Possible solutions:
- Do not parse at all the comments
- Enable to blacklist or exclude the comments on `strip` parameters or wtv

Awesome work BTW

**Comment by BrunoMiguens** [comment]
@AlexVonB I guess you're the most active maintainer, would be awesome to get some insight

**Comment by AlexVonB** [comment]
Hi Bruno,
thanks for the PR! I think just discarding comments is a good solution, we should implement it. I am going to merge your PR.
Best!
