### ISSUE TITLE
chomp optional?

### ISSUE THREAD

**Issue by BrunoMiguens** [matthewwithanm/python-markdownify#35]
I know we should not remove the `chomp` as it is might cause issues.

However, I'm using markdownify to parse some HTML to Markdown on some crawlers and so there's a lot of websites that uses the following format:
```html
<b>Text with space inside </b>rest pf the text without space
```

instead of:
```html
<b>Text with space inside</b> rest of the text without space
```

It is minor yes, although causes problems due to the parse gets like below and therefore the markdown reader can't read the text as bold:
`**Text wit space inside**rest of the text without space`

The solution might be adding an option to disallow the `chomp`. LMK what you'll think.

**Comment by AlexVonB** [comment]
Hi Bruno,
I'm not sure if I get your isse correctly. The problem with the whitespace should be solved, see the testcases in the PR that resolved the issue: https://github.com/matthewwithanm/python-markdownify/pull/14/files#diff-9367b36e95d87e540dc5f108066635f93ae0c52f54856a3e3b720b4fc72060a7R24
Are you using the latest version of this lib?
Best!

**Comment by BrunoMiguens** [comment]
I did some tests and you're right that's working fine. however did found the issue. The HTML I'm trying to parse has no space but has a `<br>` inside the `<b>` which is being ignored and therefore no new line is being created making the markdown reader not able to parse it.

```python
# Currently this test passes and represents the problem
assert md('<b>bold with br<br></b><i>italic</i>') == '**bold with br***italic*'

# We should have this output with the new line in between
assert md('<b>bold with br<br></b><i>italic</i>') == '**bold with br**\n*italic*'
```

Perhaps the issue a bit harder to solve, but creates issues as well.

**Comment by AlexVonB** [comment]
I see! Just checked what `pandoc` would do in this case:

```bash
$ echo "<b>test<br></b><i>more</i>" | pandoc -f html -t gfm -
**test  
***more*
```

I don't see an immediate way to fix this issue. The question is how far we want to go changing the intention of the HTML. An example like

```html
<b>foo</b><i>bar</i>
```

or even

```html
<b>foo</b><b>bar</b>
```

probably does not want a space in between foo and bar. We would have to check for adjacent equal tags, and whitespacetags that are not followed by text in inline tags. Probably exceeds the scope of this simple converter :/ LMK what you think.

**Comment by BrunoMiguens** [comment]
Yeah the issue is a bit harder as we would have to check inside the bold to see if there's anything else inside and parse it

**Comment by BrunoMiguens** [comment]
Yeah you're kind of right. Thought would be amazing to have it work and perhaps we might need if we add support to bold/italic/code or wtv inside each table row. The principle would be more or less the same in this issue or in tables, inside a `tr` we might have a `b` and parse it would fixe the issue in both tables and perhaps in here. 
Would have to recursively check for tags inside a already parsed tag.

**Comment by AlexVonB** [comment]
Hey! I just last week added code to process tags inside table cells. It works recursively, so I think we solved all problems in this issue that can be solved without a huge overhead :+1: Closing this issue now :)
