### ISSUE TITLE
Port to Python 3.

### ISSUE THREAD

**Issue by aknrdureegaesr** [matthewwithanm/python-markdownify#38]
According to [Pypi](https://pypi.org/project/markdownify/) and the current [`setup.py`](https://github.com/matthewwithanm/python-markdownify/blob/ed406d3206d6509b9c8c349fd92ebacaf5768729/setup.py), this is only to be used with Python 2, not yet with Python 3. I'm interested in software that does what this software does, but don't want to mess with Python 2 any longer. So a port to Python 3 would be appreciated!

**Comment by AlexVonB** [comment]
Hi! The latest version is tagged for 3.x: https://pypi.org/project/markdownify/0.6.5/ Greetings!
