### ISSUE TITLE
Tables that only use `<tr>` and `<td>` tags do not work

### ISSUE THREAD

**Issue by ju-mueller** [matthewwithanm/python-markdownify#42]
<https://github.com/matthewwithanm/python-markdownify/pull/36> added basic table support, but only for tables that use `<th>` tags for the first line instead of `<td>` tags. Tables must look like that:

```html
<table>
    <tr>
        <th>this</th>
        <th>is</th>
        <th>tableheader</th>
    </tr>
    <tr>
        <td>this</td>
        <td>is</td>
        <td>normal table data</td>
    </tr>
    <tr>
        <td>this is</td>
        <td>normal table data</td>
        <td>too</td>
    </tr>
</table>
```

which results in:

```markdown
| this | is | tableheader |
| --- | --- | --- |
| this | is | normal table data |
| this is | normal table data | too |
```

A html table that only uses `<td>` flags results in a markdown file that looks like that:

```markdown
| this | is | tableheader |
| this | is | normal table data |
| this is | normal table data | too |
```

which will not be rendered correctly because the dashed line below the header row is missing.

**Comment by AlexVonB** [comment]
Hi! Markdown tables are only valid with a header. What do you propose, should we prepend an empty header line like

```
| | |
| --- | --- | --- |
| this | is | tableheader |
| this | is | normal table data |
| this is | normal table data | too |
```

which renders as:

|  | | |
| --- | --- | --- |
| this | is | tableheader |
| this | is | normal table data |
| this is | normal table data | too |

Let me know what you had in mind!
Best, Alex

**Comment by ju-mueller** [comment]
Hi Alex,
thanks for your fast reply.
I thought about always using the first table line as header, no matter if it should be a header line or not. But I think your idea is even better to not getting confused.

Kind regards,
Julius

**Comment by AlexVonB** [comment]
I added the functionality, let me know what you think! If I dont hear from you the next days, I'll merge it and push a new release :+1:
