### ISSUE TITLE
Newlines after images

### ISSUE THREAD

**Issue by IlyaBizyaev** [matthewwithanm/python-markdownify#46]
When converting articles containing images with markdownify:
```python3
md('<img src="https://example.com/test.jpg><p>Next paragraph</p>')
```
I get the following result:
```markdown
![](https://example.com/test.jpg)Next paragraph\n\n
```
But what I normally expect is:
```markdown
![](https://example.com/test.jpg)\n\nNext paragraph\n\n
```
Is it possible to add a flag to put newlines after images, or even make it the default behavior?

**Comment by AlexVonB** [comment]
Hey!
Images are inline elements: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#styling_with_css So if someone includes an image like this emoji :+1: inline with some text, a newline would not be desired. Inline elements should also only be included within some block element, like `<p>`  or `<div>`. So the default behavior should never be to add newlines after images. Even a flag does not make much sense, since your use case is very narrow. You could inherit your own image converter: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#styling_with_css
Best, Alex

**Comment by IlyaBizyaev** [comment]
Thank you for the explanation, I will inherit a converter :)

It looks like most websites use images as block elements by changing their `display` CSS property or putting them in a block element like `<div>`. While the emoji use case still does exist, it appears to be significantly less common. So converting article-like web pages (blogs, news) to Markdown results in images being incorrectly prepended to the following paragraph.

**Comment by IlyaBizyaev** [comment]
Converter inheritance fails when the image is wrapped in `<a>`, because the `chomp` function strips trailing newlines:
https://github.com/matthewwithanm/python-markdownify/blob/62e9f0de0258088412dc41f251d07c10bab0d0b8/markdownify/__init__.py#L34-L44

**Comment by AlexVonB** [comment]
Please post a minimam HTML example that shows the error. Thanks!

**Comment by IlyaBizyaev** [comment]
For `md()` from https://github.com/matthewwithanm/python-markdownify#creating-custom-converters,

```python3
md('<a href="/image-full.png"><img alt="Image" src="/image-small.png"></a>')
```
### Expected:
```md
[![Image](/image-small.png)](/image-full.png)\n\n
```
### Actual
```md
[![Image](/image-small.png)](/image-full.png)
```

**Comment by AlexVonB** [comment]
Ah I see! If you want a new line after a link that contains an image, you have to override the `convert_a`, too. Something like this could help you:

```python
    def convert_a(self, el, text, convert_as_inline):
        if 'img' in [c.name for c in el.children]:
            return super().convert_a(el, text, convert_as_inline) + '\n\n'
        return super().convert_a(el, text, convert_as_inline)
```

Since this is an even more niche case, I will close this issue again.

**Comment by IlyaBizyaev** [comment]
There's nothing niche about these, I'm literally converting blog posts to Markdown that could be used to generate them :)

https://blog.broulik.de/2021/06/blast-from-the-past-icon-dialog/

**Comment by AlexVonB** [comment]
The images in your link are embedded as figures between paragraphs:

```html
<p>You know you’re up for an exciting task when the files ...</p>

<figure><a href="http://blog.broulik.de/wp-content/uploads/2021/02/icondialognice5.png"><img src="http://blog.broulik.de/wp-content/uploads/2021/02/icondialognice5-1024x582.png"/></a><figcaption>Original icon dialog redesign from 2013</figcaption></figure>

<p>The dialog was programmatically built in C++ ...</p>
```

This compiles to

```markdown
You know you’re up for an exciting task when the files ...


[![The same dialog as in the teaser image, albeit slightly "dated" with 2010's era skeumorphic icons and gradients](http://blog.broulik.de/wp-content/uploads/2021/02/icondialognice5-1024x582.png)](http://blog.broulik.de/wp-content/uploads/2021/02/icondialognice5.png)Original icon dialog redesign from 2013
The dialog was programmatically built in C++ ...
```

aka

>You know you’re up for an exciting task when the files ...
>
>[![The same dialog as in the teaser image, albeit slightly "dated" with 2010's era skeumorphic icons and gradients](http://blog.broulik.de/wp-content/uploads/2021/02/icondialognice5-1024x582.png)](http://blog.broulik.de/wp-content/uploads/2021/02/icondialognice5.png)Original icon dialog redesign from 2013
The dialog was programmatically built in C++ ...

This is rather an issue with the `figure` and `caption` tag than with a newline after images or links. Let me know what you think!

**Comment by IlyaBizyaev** [comment]
> icondialognice5.png)Original icon dialog redesign from 2013

This is not specific to `caption`: any text following an image in blog posts should never be on the same line (none of the blogs I dealt with used image emojis).

**Comment by AlexVonB** [comment]
I just added support for `figure` and `figcaption`. `figure` is a [flow element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure), just like `img`, so a forced newline after it does not make sense. If you want to have your images or figures as block elements, you have to add some style to your markdown or override the `convert_figure` method.

**Comment by IlyaBizyaev** [comment]
I'm not sure I see this as an improvement :(

With the proposed `convert_a` override, everything worked as expected: I got human-readable and correct Markdown. I did handle `figcaption` separately, but only for styling purposes:
https://invent.kde.org/ilyabizyaev/ru-promo-scripts/-/blob/master/html_selector.py#L66

Now I have to also workaround HTML tags in Markdown output :(

**Comment by AlexVonB** [comment]
I'm afraid that inline HTML [is standard in Markdown](https://daringfireball.net/projects/markdown/syntax#html) :/ I see your problems, but I hesitate greatly to change the logic of flow elements just for your project :( I'm really sory I cannot help you. Did you try something like [pandoc](https://github.com/boisgera/pandoc/tree/1.x)?

**Comment by IlyaBizyaev** [comment]
It would help to describe in the README what the intended use case for this library is. I'm sure there are many other cases where the expected behavior will differ depending on the project.
