### ISSUE TITLE
Don't escape characters when between backticks

### ISSUE THREAD

**Issue by mvantellingen** [matthewwithanm/python-markdownify#47]
If i'm understanding the spec correctly we shouldn't have to escape for example underscores when the value is between a backticks.

eg.

```
`this_should_not_escape` -> `this\_should\_not\_escape`
```

**Comment by AlexVonB** [comment]
Thanks! This is fixed in [0.9.1](https://github.com/matthewwithanm/python-markdownify/releases/tag/0.9.1)
