### ISSUE TITLE
Tables not converted well.

### ISSUE THREAD

**Issue by wom-bat** [matthewwithanm/python-markdownify#49]
Here is a test case:
```python
from markdownify import markdownify as md

text="""
<html>
  <body>
    <table>
      <thead>
	<tr>
	  <th>
	    <p>Heading 1</p>
	  </th>
	  <th><p>Heading 2</p>
	  </th>
	  <th><p>Heading 3</p>
	  </th>
	</tr>
      </thead>
      <tbody>
	<tr>
	  <td><div><p>
		This is some text for the first column.
	    </p></div>
	  </td>
	  <td colspan=2>
	    <div><p>
		This is the rest of the columns.
	      </p>
	    </div>
	  </td>
      </tbody>
    </table>
  </body>
</html>
"""

print(md(text))
```
The result cannot be rendered by any markdown engine I know of.

**Comment by AlexVonB** [comment]
Hi!

A paragraph is converted as newlines around it, and this breaks the table environment in markdown. I fixed this in 0fdeb1f.

Col/Rowspan is not suppported by any Markdown spec I know of. As you can use HTML in Markdown, you could manually add these special tables to your final Markdown file.

Best
