### ISSUE TITLE
convert_list needs a trailing linefeed

### ISSUE THREAD

**Issue by jj-jitterbit** [matthewwithanm/python-markdownify#5]
I'm seeing that code such as
`<ul><li>foo</li></ul><p>bar</p>`

is being returned as `u'* foo\nbar\n\n'` when it really needs to be `u'* foo\n\nbar\n\n'`. Otherwise, the text `bar` is seen as part of the list when in fact it is a new paragraph and should not be indented.

A fix is changing the method `convert_list` to end with:
```
return text + '\n'
```

**Comment by matthewwithanm** [comment]
I'll merge a PR if you've got it! (Tests appreciated)
