### ISSUE TITLE
No option to select a class name to whitelist or exclude?

### ISSUE THREAD

**Issue by thinkhuman** [matthewwithanm/python-markdownify#50]
The most common scenario for me is to select specific class names (e.g., div class='foo') I want to convert, not just tags. I don't see that option--is it possible?

**Comment by danisztls** [comment]
> Alright, I see. In this case, the convert/strip options are not what you are looking for. These options enable/disable specific tags while converting the rest of the HTML document normally.
> 
> What you want is to [parse](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#making-the-soup) the HTML document with BeautifulSoup, [select](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#css-selectors) the subtree you want using a CSS selector like `.foo`, [get the contents](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#get-text) and save your list. At least I think that's what you want :D let me know if it is a problem we can help with.

I'm doing this. :smile:  In my case performance is not being an issue but as a suggestion could Markdownify also accept a BeautifulSoup HTML tree additionally to the HTML string? This way we would avoid parsing the document twice.

**Comment by AlexVonB** [comment]
Hi, I added the function to do so: https://github.com/matthewwithanm/python-markdownify#converting-beautifulsoup-objects It is present in 0.10.3. Best, Alex

**Comment by danisztls** [comment]
@AlexVonB Thanks! Working as expected. There's only a typo on the usage section.

It says:
`return ImageBlockConverter(**options).convert_soup(soup)`

Where it should be:
`return MarkdownConverter(**options).convert_soup(soup)`

**Comment by AlexVonB** [comment]
Good catch, thank you!
