### ISSUE TITLE
Can you provide an option to disable text escaping?

### ISSUE THREAD

**Issue by RyouMon** [matthewwithanm/python-markdownify#59]
For example, when I convert `<p>INVALID_ERROR_CODE</p>`, I got `INVALID\_ERROR\_CODE`, but I want `INVALID_ERROR_CODE`.

So I must call `text.replace(r'\_', '_')`. That's too slow when processing long text.

Can I get any help? Thanks.

**Comment by RyouMon** [comment]
As REAMD.md describes, I create my custom Converter, and rewirte `process_text` method.

Now it works for me.

**Comment by AlexVonB** [comment]
Hi, you can use

https://github.com/matthewwithanm/python-markdownify/blob/d3eff116177cf245cae8ce8d6a79e853cf9b5a43/tests/test_escaping.py#L6

for this now.
Best

**Comment by RyouMon** [comment]
Thank you very much.
