### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Lqp1** [matthewwithanm/python-markdownify#6]
Hi,

I'm interested in using your module, but I can't find any licensing info. Can you provide one please ?

Thanks :)

**Comment by matthewwithanm** [comment]
Hey @lqp1! It should just be MIT I think. Wanna open a PR with a LICENSE file?

**Comment by Lqp1** [comment]
Hi ! I opened a PR; this is my first one but tried to do my best :)

**Comment by matthewwithanm** [comment]
Thanks!
