### ISSUE TITLE
Doesn't properly convert image inside table

### ISSUE THREAD

**Issue by bertmad3400** [matthewwithanm/python-markdownify#61]
Take the following html as an example:

`<table> <tbody> <tr> <td> <img src="https://avatars.githubusercontent.com/u/57845632?s=400&u=48a7889c50d234959a518020779ae2dd0c1e6546&v=4"> </td> </tr> </tbody> </table>`

When running this through markdownify, it for some reason doesn't produce a markdown table, with an image, but simply a table, like this:

`\n\n|  |\n\n`

Why this happens is not yet clear to me.

**Comment by AlexVonB** [comment]
Thanks for your issue! I added the option `keep_inline_images_in`, it will be available in the next release (next few days).
