### ISSUE TITLE
Should the <scripts> be rendered?

### ISSUE THREAD

**Issue by Sky-NiniKo** [matthewwithanm/python-markdownify#69]
Basic exemple:
```py
import markdownify
print(markdownify.markdownify('<script>console.log(1+1)</script>'))
```
Output:
```py
'console.log(1+1)'
```
Is this the expected behavior?

**Comment by AlexVonB** [comment]
Hi, what did you expect the output to be? If you want to not convert the script tag at all, use a [custom converter](https://github.com/matthewwithanm/python-markdownify#creating-custom-converters) to handle the conversion of the script tag. If you have input on how to handle script tags generally, let me know, we might put it into the code. Best

**Comment by AlexVonB** [comment]
Thanks for your effort! I will add an option to ignore tags, until then you can use

```python
from markdownify import MarkdownConverter

class IgnoringScriptConverter(MarkdownConverter):
    """
    Create a custom MarkdownConverter that ignores script tags
    """
    def convert_script(self, el, text, convert_as_inline):
        return ''

# Create shorthand method for conversion
def md(html, **options):
    return IgnoringScriptConverter(**options).convert(html)
```

Best! Alex
