### ISSUE TITLE
Linting tool flake8 is not a build dependency

### ISSUE THREAD

**Issue by McSinyx** [matthewwithanm/python-markdownify#70]
Building and installing markdownify should not fetch flake8, which is only used during the development of the package.  Per https://github.com/pypa/setuptools/issues/931, `tests_require` should also be removed, in favor of alternative test runners such as tox.  I can offer a hand if migration is desired.

**Comment by AlexVonB** [comment]
Hi @McSinyx sorry for the delay. Removing flake8 from the setup requirements is a no-brainer, thank you! What do you propose for the replacement of tests_required? I'm happy to receive some hints!

**Comment by AlexVonB** [comment]
Fixed in https://pypi.org/project/markdownify/0.11.4/ :)

**Comment by McSinyx** [comment]
Thanks!
