### ISSUE TITLE
ASTERISK instead of * for invalid HTML

### ISSUE THREAD

**Issue by cukabeka** [matthewwithanm/python-markdownify#75]
I have the weird case with [0.11.5](https://github.com/matthewwithanm/python-markdownify/releases/tag/0.11.5) now, that in the output, all `*` chars (also those used for marking a text portion as bold) just output `ASTERISK` instead, resulting in texts like this:

input (yes, I know, this is VERY messy and invalid HTML, but this is coming from a messy CMS I want to clean up):
```
<h2 class="">
<div class="s-component-content s-font-title">
<h2>
<p style="font-size: 130%;">
<strong>Experience</strong>
</p>
</h2>
</div>
</h2>
```

output: 
`* ASTERISKASTERISKExperienceASTERISKASTERISK`

But subsequently even bolding does not work anymore:

Input
`<p>Normal <strong>bold</strong> text.</p>`
Output
`Normal ASTERISKASTERISKboldASTERISKASTERISK text.`

Is there any way to circumvent this using markdownify? Or any way to preprocess/postprocess these cases using this script?

**Comment by AlexVonB** [comment]
Well, that was an oversight on my part :D Now it should work as advertised! (Use v0.11.6)
