### ISSUE TITLE
How to include lazy loaded image in converted md document?

### ISSUE THREAD

**Issue by dimritium** [matthewwithanm/python-markdownify#77]
HTML that I am trying to parse has img tag like below:
```html
<img loading="lazy" class="sub-img alignleft wp-image-164 size-full" src="http://zerodha.com/varsity/wp-content/uploads/2014/07/equity-icon1.png" alt="equity-icon1" width="131" height="131">
```
Markdown document fails to render this image. Should I use regex parse to remove `loading="lazy"` or there is a way to do in markdownify?

**Comment by AlexVonB** [comment]
Hi! When I run your tag through markdownify it converts to `![equity-icon](http://zeroda....../equity-icon1.png)` thus working as intended. Does your markdown renderer not like non-https-resources (or your browser blocks them, I hope)?

**Comment by dimritium** [comment]
Yeah sorry, it's working fine. Maybe I messed up something with beautiful soup object earlier.

Thanks!
