### ISSUE TITLE
ordered list issue

### ISSUE THREAD

**Issue by hsmett** [matthewwithanm/python-markdownify#8]
Hello :)

I encountered a probleme markdownifying ordered lists:

given `html = '<ol>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n</ol>'`

the ol node list is: `['\n', <li>w</li>, '\n', <li>t</li>, '\n', <li>f</li>, '\n']`

as `bullet = '%s.' % (parent.index(el) + 1)`,

the result is:

```
: markdownify(html)
: ' 2. a\n 4. b\n 6. c\n '
```
<=>
```
 2. a
 4. b
 6. c
```

I could preprocess my html input before passing it to markdonify but I'm affraid to loose "meaningfull linebreaks" if such things even exist ^^
I think this might be handled in the library, what do you think?

Thank you !

**Comment by jszwedko** [comment]
Seeing this as well. I pre-processed it using beautifulsoup to remove the newlines, but I agree that it'd be nice for the library to handle this if possible.

**Comment by matthewwithanm** [comment]
Any chance of getting a PR with some tests? 😈

**Comment by widal001** [comment]
Running into this issue as well, @jszwedko what pre-processing did you do?

**Comment by spu95** [comment]
my fix 
```
 # this hack fixes the ol number problem with blank lines
    def index_without_blanks(self, parent, el):
        index = parent.index(el)
        j = 0
        blanks = 0
        for child in parent.children:
            if j == index:
                break
            if str(child) == "\n":
                blanks = blanks + 1
            j = j + 1
        return index - blanks

    def convert_li(self, el, text, convert_as_inline):
        parent = el.parent
        if parent is not None and parent.name == 'ol':
            if parent.get("start"):
                start = int(parent.get("start"))
            else:
                start = 1
            bullet = '%s.' % (start + self.index_without_blanks(parent, el))
        else:
            depth = -1
            while el:
                if el.name == 'ul':
                    depth += 1
                el = el.parent
            bullets = self.options['bullets']
            bullet = bullets[depth % len(bullets)]
        return '%s %s\n' % (bullet, text or '')
```
