### ISSUE TITLE
Whitespace is removed in code

### ISSUE THREAD

**Issue by JamesDConley** [matthewwithanm/python-markdownify#85]
When converting html with `<code>` blocks the whitespace ends up with a maximum of one space. This unfortunately means anything with python in codeblocks can't be converted :(

**Comment by kelibird** [comment]
![image](https://user-images.githubusercontent.com/18713658/223968748-c2cc4ec8-bfa9-4e00-8ff3-73e33759363a.png)

**Comment by Meathelix1** [comment]
> ![image](https://user-images.githubusercontent.com/18713658/223968748-c2cc4ec8-bfa9-4e00-8ff3-73e33759363a.png)

Thanks! Was wondering why my code was doing this.

**Comment by chrispy-snps** [comment]
I don't think this is a bug. `<code>` is an inline HTML element per the specification, and thus it does not preserve whitespace. If you render

```
<code>line1
line2
line3</code>
```

in a browser, all three words will be on a single line.

You need to enclose your code in a `<pre>` block, which is whitespace-preserved per the specification.
