### ISSUE TITLE
Tidy HTML breaks result

### ISSUE THREAD

**Issue by nachitox** [matthewwithanm/python-markdownify#88]
On version `0.11.6` when I run:

```
markdownify("<h2>\n\tHeadline 2 on new line\n</h2>", heading_style="ATX")
```

I expect this:

```
## Headline 2 on new line\n\n
```

but I get this:

```
'## \n Headline 2 on new line\n\n'
```

which I believe is a bug.

**Comment by 5yato4ok** [comment]
Yes, I believe a tiny fix should remove the bug. https://github.com/matthewwithanm/python-markdownify/pull/89

**Comment by mirabilos** [comment]
Possibly a duplicate of https://github.com/matthewwithanm/python-markdownify/issues/31 (and see my comment there, maybe the code snippet helps?)
