### ISSUE TITLE
wrong license in setup.py

### ISSUE THREAD

**Issue by jvanasco** [matthewwithanm/python-markdownify#9]
You include the MIT license, but `setup.py` notes the BSD license.

https://github.com/matthewwithanm/python-markdownify/blob/develop/setup.py#L85

**Comment by matthewwithanm** [comment]
woops. any chance you could submit a PR? whichever is more permissive is fine.

**Comment by jvanasco** [comment]
sure. they're basically the same, so I just changed it to MIT with a browser edit.

thanks for releasing this. i actually had to write a converter myself (some specific requirements, including using html5lib) but took some of your unit tests and saw this discrepancy when trying to credit you ;)
