### ISSUE TITLE
Inline <p> not handled well

### ISSUE THREAD

**Issue by mirabilos** [matthewwithanm/python-markdownify#92]
Input:

    Wie nennt man jemanden, der gegen Covid-Politik Proteste organisiert, und sich dann mit einem Covid-Testcenter an der Zitze des Staates labt?<p><a href="https://www.mdr.de/nachrichten/sachsen-anhalt/dessau/bitterfeld/buergermeister-raguhn-jessnitz-loth-afd-100.html">Bürgermeister und AfD-Abgeordneter</a>.

Proposed patch:

    -        return '%s\n\n' % text if text else ''
    +        return '\n\n%s\n\n' % text if text else ''

Unsure if the newlines _after_ actually need to be there, but, sure, why not. People have to postprocess the output of this to clean up newlines anyway.

**Comment by chrispy-snps** [comment]
Smaller testcase:

```
>>> from markdownify import markdownify as md
>>> md('TEXT1<p>TEXT2</p>')
'TEXT1TEXT2\n\n'
```

There is no line break before the TEXT2 paragraph content.
