### ISSUE TITLE
Angle brackets <> aren't escaped.

### ISSUE THREAD

**Issue by AnyOldName3** [matthewwithanm/python-markdownify#99]
```py
>>> markdownify('text&lt;text&gt;')                              
'text<text>'
```
In at least some flavours of Markdown, this would need to be `text\<text\>` instead. As an example, GitHub-flavoured Markdown gives

text<text>

and

text\<text\>

without and with backslashes respectively.

**Comment by chrispy-snps** [comment]
@AnyOldName3 - I am not familiar with the various Markdown variants available. Are you aware of any Markdown variants where angle brackets _aren't_ escaped? The only rule I am aware of is to escape them everywhere except in preformatted text spans and blocks.
